	dev_hps u0 (
		.bus_clock_clk                    (<connected-to-bus_clock_clk>),                    //            bus_clock.clk
		.bus_reset_reset_n                (<connected-to-bus_reset_reset_n>),                //            bus_reset.reset_n
		.hps_ddr_mem_a                    (<connected-to-hps_ddr_mem_a>),                    //              hps_ddr.mem_a
		.hps_ddr_mem_ba                   (<connected-to-hps_ddr_mem_ba>),                   //                     .mem_ba
		.hps_ddr_mem_ck                   (<connected-to-hps_ddr_mem_ck>),                   //                     .mem_ck
		.hps_ddr_mem_ck_n                 (<connected-to-hps_ddr_mem_ck_n>),                 //                     .mem_ck_n
		.hps_ddr_mem_cke                  (<connected-to-hps_ddr_mem_cke>),                  //                     .mem_cke
		.hps_ddr_mem_cs_n                 (<connected-to-hps_ddr_mem_cs_n>),                 //                     .mem_cs_n
		.hps_ddr_mem_ras_n                (<connected-to-hps_ddr_mem_ras_n>),                //                     .mem_ras_n
		.hps_ddr_mem_cas_n                (<connected-to-hps_ddr_mem_cas_n>),                //                     .mem_cas_n
		.hps_ddr_mem_we_n                 (<connected-to-hps_ddr_mem_we_n>),                 //                     .mem_we_n
		.hps_ddr_mem_reset_n              (<connected-to-hps_ddr_mem_reset_n>),              //                     .mem_reset_n
		.hps_ddr_mem_dq                   (<connected-to-hps_ddr_mem_dq>),                   //                     .mem_dq
		.hps_ddr_mem_dqs                  (<connected-to-hps_ddr_mem_dqs>),                  //                     .mem_dqs
		.hps_ddr_mem_dqs_n                (<connected-to-hps_ddr_mem_dqs_n>),                //                     .mem_dqs_n
		.hps_ddr_mem_odt                  (<connected-to-hps_ddr_mem_odt>),                  //                     .mem_odt
		.hps_ddr_mem_dm                   (<connected-to-hps_ddr_mem_dm>),                   //                     .mem_dm
		.hps_ddr_oct_rzqin                (<connected-to-hps_ddr_oct_rzqin>),                //                     .oct_rzqin
		.hps_f2h_axi_slave_awid           (<connected-to-hps_f2h_axi_slave_awid>),           //    hps_f2h_axi_slave.awid
		.hps_f2h_axi_slave_awaddr         (<connected-to-hps_f2h_axi_slave_awaddr>),         //                     .awaddr
		.hps_f2h_axi_slave_awlen          (<connected-to-hps_f2h_axi_slave_awlen>),          //                     .awlen
		.hps_f2h_axi_slave_awsize         (<connected-to-hps_f2h_axi_slave_awsize>),         //                     .awsize
		.hps_f2h_axi_slave_awburst        (<connected-to-hps_f2h_axi_slave_awburst>),        //                     .awburst
		.hps_f2h_axi_slave_awlock         (<connected-to-hps_f2h_axi_slave_awlock>),         //                     .awlock
		.hps_f2h_axi_slave_awcache        (<connected-to-hps_f2h_axi_slave_awcache>),        //                     .awcache
		.hps_f2h_axi_slave_awprot         (<connected-to-hps_f2h_axi_slave_awprot>),         //                     .awprot
		.hps_f2h_axi_slave_awvalid        (<connected-to-hps_f2h_axi_slave_awvalid>),        //                     .awvalid
		.hps_f2h_axi_slave_awready        (<connected-to-hps_f2h_axi_slave_awready>),        //                     .awready
		.hps_f2h_axi_slave_awuser         (<connected-to-hps_f2h_axi_slave_awuser>),         //                     .awuser
		.hps_f2h_axi_slave_wid            (<connected-to-hps_f2h_axi_slave_wid>),            //                     .wid
		.hps_f2h_axi_slave_wdata          (<connected-to-hps_f2h_axi_slave_wdata>),          //                     .wdata
		.hps_f2h_axi_slave_wstrb          (<connected-to-hps_f2h_axi_slave_wstrb>),          //                     .wstrb
		.hps_f2h_axi_slave_wlast          (<connected-to-hps_f2h_axi_slave_wlast>),          //                     .wlast
		.hps_f2h_axi_slave_wvalid         (<connected-to-hps_f2h_axi_slave_wvalid>),         //                     .wvalid
		.hps_f2h_axi_slave_wready         (<connected-to-hps_f2h_axi_slave_wready>),         //                     .wready
		.hps_f2h_axi_slave_bid            (<connected-to-hps_f2h_axi_slave_bid>),            //                     .bid
		.hps_f2h_axi_slave_bresp          (<connected-to-hps_f2h_axi_slave_bresp>),          //                     .bresp
		.hps_f2h_axi_slave_bvalid         (<connected-to-hps_f2h_axi_slave_bvalid>),         //                     .bvalid
		.hps_f2h_axi_slave_bready         (<connected-to-hps_f2h_axi_slave_bready>),         //                     .bready
		.hps_f2h_axi_slave_arid           (<connected-to-hps_f2h_axi_slave_arid>),           //                     .arid
		.hps_f2h_axi_slave_araddr         (<connected-to-hps_f2h_axi_slave_araddr>),         //                     .araddr
		.hps_f2h_axi_slave_arlen          (<connected-to-hps_f2h_axi_slave_arlen>),          //                     .arlen
		.hps_f2h_axi_slave_arsize         (<connected-to-hps_f2h_axi_slave_arsize>),         //                     .arsize
		.hps_f2h_axi_slave_arburst        (<connected-to-hps_f2h_axi_slave_arburst>),        //                     .arburst
		.hps_f2h_axi_slave_arlock         (<connected-to-hps_f2h_axi_slave_arlock>),         //                     .arlock
		.hps_f2h_axi_slave_arcache        (<connected-to-hps_f2h_axi_slave_arcache>),        //                     .arcache
		.hps_f2h_axi_slave_arprot         (<connected-to-hps_f2h_axi_slave_arprot>),         //                     .arprot
		.hps_f2h_axi_slave_arvalid        (<connected-to-hps_f2h_axi_slave_arvalid>),        //                     .arvalid
		.hps_f2h_axi_slave_arready        (<connected-to-hps_f2h_axi_slave_arready>),        //                     .arready
		.hps_f2h_axi_slave_aruser         (<connected-to-hps_f2h_axi_slave_aruser>),         //                     .aruser
		.hps_f2h_axi_slave_rid            (<connected-to-hps_f2h_axi_slave_rid>),            //                     .rid
		.hps_f2h_axi_slave_rdata          (<connected-to-hps_f2h_axi_slave_rdata>),          //                     .rdata
		.hps_f2h_axi_slave_rresp          (<connected-to-hps_f2h_axi_slave_rresp>),          //                     .rresp
		.hps_f2h_axi_slave_rlast          (<connected-to-hps_f2h_axi_slave_rlast>),          //                     .rlast
		.hps_f2h_axi_slave_rvalid         (<connected-to-hps_f2h_axi_slave_rvalid>),         //                     .rvalid
		.hps_f2h_axi_slave_rready         (<connected-to-hps_f2h_axi_slave_rready>),         //                     .rready
		.hps_f2h_irq0_irq                 (<connected-to-hps_f2h_irq0_irq>),                 //         hps_f2h_irq0.irq
		.hps_f2h_irq1_irq                 (<connected-to-hps_f2h_irq1_irq>),                 //         hps_f2h_irq1.irq
		.hps_h2f_100mhz_clock_clk         (<connected-to-hps_h2f_100mhz_clock_clk>),         // hps_h2f_100mhz_clock.clk
		.hps_h2f_50mhz_clock_clk          (<connected-to-hps_h2f_50mhz_clock_clk>),          //  hps_h2f_50mhz_clock.clk
		.hps_h2f_axi_master_awid          (<connected-to-hps_h2f_axi_master_awid>),          //   hps_h2f_axi_master.awid
		.hps_h2f_axi_master_awaddr        (<connected-to-hps_h2f_axi_master_awaddr>),        //                     .awaddr
		.hps_h2f_axi_master_awlen         (<connected-to-hps_h2f_axi_master_awlen>),         //                     .awlen
		.hps_h2f_axi_master_awsize        (<connected-to-hps_h2f_axi_master_awsize>),        //                     .awsize
		.hps_h2f_axi_master_awburst       (<connected-to-hps_h2f_axi_master_awburst>),       //                     .awburst
		.hps_h2f_axi_master_awlock        (<connected-to-hps_h2f_axi_master_awlock>),        //                     .awlock
		.hps_h2f_axi_master_awcache       (<connected-to-hps_h2f_axi_master_awcache>),       //                     .awcache
		.hps_h2f_axi_master_awprot        (<connected-to-hps_h2f_axi_master_awprot>),        //                     .awprot
		.hps_h2f_axi_master_awvalid       (<connected-to-hps_h2f_axi_master_awvalid>),       //                     .awvalid
		.hps_h2f_axi_master_awready       (<connected-to-hps_h2f_axi_master_awready>),       //                     .awready
		.hps_h2f_axi_master_wid           (<connected-to-hps_h2f_axi_master_wid>),           //                     .wid
		.hps_h2f_axi_master_wdata         (<connected-to-hps_h2f_axi_master_wdata>),         //                     .wdata
		.hps_h2f_axi_master_wstrb         (<connected-to-hps_h2f_axi_master_wstrb>),         //                     .wstrb
		.hps_h2f_axi_master_wlast         (<connected-to-hps_h2f_axi_master_wlast>),         //                     .wlast
		.hps_h2f_axi_master_wvalid        (<connected-to-hps_h2f_axi_master_wvalid>),        //                     .wvalid
		.hps_h2f_axi_master_wready        (<connected-to-hps_h2f_axi_master_wready>),        //                     .wready
		.hps_h2f_axi_master_bid           (<connected-to-hps_h2f_axi_master_bid>),           //                     .bid
		.hps_h2f_axi_master_bresp         (<connected-to-hps_h2f_axi_master_bresp>),         //                     .bresp
		.hps_h2f_axi_master_bvalid        (<connected-to-hps_h2f_axi_master_bvalid>),        //                     .bvalid
		.hps_h2f_axi_master_bready        (<connected-to-hps_h2f_axi_master_bready>),        //                     .bready
		.hps_h2f_axi_master_arid          (<connected-to-hps_h2f_axi_master_arid>),          //                     .arid
		.hps_h2f_axi_master_araddr        (<connected-to-hps_h2f_axi_master_araddr>),        //                     .araddr
		.hps_h2f_axi_master_arlen         (<connected-to-hps_h2f_axi_master_arlen>),         //                     .arlen
		.hps_h2f_axi_master_arsize        (<connected-to-hps_h2f_axi_master_arsize>),        //                     .arsize
		.hps_h2f_axi_master_arburst       (<connected-to-hps_h2f_axi_master_arburst>),       //                     .arburst
		.hps_h2f_axi_master_arlock        (<connected-to-hps_h2f_axi_master_arlock>),        //                     .arlock
		.hps_h2f_axi_master_arcache       (<connected-to-hps_h2f_axi_master_arcache>),       //                     .arcache
		.hps_h2f_axi_master_arprot        (<connected-to-hps_h2f_axi_master_arprot>),        //                     .arprot
		.hps_h2f_axi_master_arvalid       (<connected-to-hps_h2f_axi_master_arvalid>),       //                     .arvalid
		.hps_h2f_axi_master_arready       (<connected-to-hps_h2f_axi_master_arready>),       //                     .arready
		.hps_h2f_axi_master_rid           (<connected-to-hps_h2f_axi_master_rid>),           //                     .rid
		.hps_h2f_axi_master_rdata         (<connected-to-hps_h2f_axi_master_rdata>),         //                     .rdata
		.hps_h2f_axi_master_rresp         (<connected-to-hps_h2f_axi_master_rresp>),         //                     .rresp
		.hps_h2f_axi_master_rlast         (<connected-to-hps_h2f_axi_master_rlast>),         //                     .rlast
		.hps_h2f_axi_master_rvalid        (<connected-to-hps_h2f_axi_master_rvalid>),        //                     .rvalid
		.hps_h2f_axi_master_rready        (<connected-to-hps_h2f_axi_master_rready>),        //                     .rready
		.hps_h2f_reset_reset_n            (<connected-to-hps_h2f_reset_reset_n>),            //        hps_h2f_reset.reset_n
		.hps_io_hps_io_emac1_inst_TX_CLK  (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>),  //               hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0    (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),    //                     .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1    (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),    //                     .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2    (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),    //                     .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3    (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),    //                     .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0    (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),    //                     .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO    (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),    //                     .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC     (<connected-to-hps_io_hps_io_emac1_inst_MDC>),     //                     .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL  (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>),  //                     .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL  (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>),  //                     .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK  (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>),  //                     .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1    (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),    //                     .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2    (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),    //                     .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3    (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),    //                     .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_qspi_inst_SS1      (<connected-to-hps_io_hps_io_qspi_inst_SS1>),      //                     .hps_io_qspi_inst_SS1
		.hps_io_hps_io_qspi_inst_IO0      (<connected-to-hps_io_hps_io_qspi_inst_IO0>),      //                     .hps_io_qspi_inst_IO0
		.hps_io_hps_io_qspi_inst_IO1      (<connected-to-hps_io_hps_io_qspi_inst_IO1>),      //                     .hps_io_qspi_inst_IO1
		.hps_io_hps_io_qspi_inst_IO2      (<connected-to-hps_io_hps_io_qspi_inst_IO2>),      //                     .hps_io_qspi_inst_IO2
		.hps_io_hps_io_qspi_inst_IO3      (<connected-to-hps_io_hps_io_qspi_inst_IO3>),      //                     .hps_io_qspi_inst_IO3
		.hps_io_hps_io_qspi_inst_SS0      (<connected-to-hps_io_hps_io_qspi_inst_SS0>),      //                     .hps_io_qspi_inst_SS0
		.hps_io_hps_io_qspi_inst_CLK      (<connected-to-hps_io_hps_io_qspi_inst_CLK>),      //                     .hps_io_qspi_inst_CLK
		.hps_io_hps_io_sdio_inst_CMD      (<connected-to-hps_io_hps_io_sdio_inst_CMD>),      //                     .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0       (<connected-to-hps_io_hps_io_sdio_inst_D0>),       //                     .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1       (<connected-to-hps_io_hps_io_sdio_inst_D1>),       //                     .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK      (<connected-to-hps_io_hps_io_sdio_inst_CLK>),      //                     .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2       (<connected-to-hps_io_hps_io_sdio_inst_D2>),       //                     .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3       (<connected-to-hps_io_hps_io_sdio_inst_D3>),       //                     .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0       (<connected-to-hps_io_hps_io_usb1_inst_D0>),       //                     .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1       (<connected-to-hps_io_hps_io_usb1_inst_D1>),       //                     .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2       (<connected-to-hps_io_hps_io_usb1_inst_D2>),       //                     .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3       (<connected-to-hps_io_hps_io_usb1_inst_D3>),       //                     .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4       (<connected-to-hps_io_hps_io_usb1_inst_D4>),       //                     .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5       (<connected-to-hps_io_hps_io_usb1_inst_D5>),       //                     .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6       (<connected-to-hps_io_hps_io_usb1_inst_D6>),       //                     .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7       (<connected-to-hps_io_hps_io_usb1_inst_D7>),       //                     .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK      (<connected-to-hps_io_hps_io_usb1_inst_CLK>),      //                     .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP      (<connected-to-hps_io_hps_io_usb1_inst_STP>),      //                     .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR      (<connected-to-hps_io_hps_io_usb1_inst_DIR>),      //                     .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT      (<connected-to-hps_io_hps_io_usb1_inst_NXT>),      //                     .hps_io_usb1_inst_NXT
		.hps_io_hps_io_uart0_inst_RX      (<connected-to-hps_io_hps_io_uart0_inst_RX>),      //                     .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX      (<connected-to-hps_io_hps_io_uart0_inst_TX>),      //                     .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA      (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),      //                     .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL      (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),      //                     .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA      (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),      //                     .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL      (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),      //                     .hps_io_i2c1_inst_SCL
		.hps_io_hps_io_can0_inst_RX       (<connected-to-hps_io_hps_io_can0_inst_RX>),       //                     .hps_io_can0_inst_RX
		.hps_io_hps_io_can0_inst_TX       (<connected-to-hps_io_hps_io_can0_inst_TX>),       //                     .hps_io_can0_inst_TX
		.hps_io_hps_io_can1_inst_RX       (<connected-to-hps_io_hps_io_can1_inst_RX>),       //                     .hps_io_can1_inst_RX
		.hps_io_hps_io_can1_inst_TX       (<connected-to-hps_io_hps_io_can1_inst_TX>),       //                     .hps_io_can1_inst_TX
		.hps_io_hps_io_gpio_inst_GPIO00   (<connected-to-hps_io_hps_io_gpio_inst_GPIO00>),   //                     .hps_io_gpio_inst_GPIO00
		.hps_io_hps_io_gpio_inst_GPIO09   (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),   //                     .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO28   (<connected-to-hps_io_hps_io_gpio_inst_GPIO28>),   //                     .hps_io_gpio_inst_GPIO28
		.hps_io_hps_io_gpio_inst_GPIO40   (<connected-to-hps_io_hps_io_gpio_inst_GPIO40>),   //                     .hps_io_gpio_inst_GPIO40
		.hps_io_hps_io_gpio_inst_GPIO41   (<connected-to-hps_io_hps_io_gpio_inst_GPIO41>),   //                     .hps_io_gpio_inst_GPIO41
		.hps_io_hps_io_gpio_inst_LOANIO37 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO37>), //                     .hps_io_gpio_inst_LOANIO37
		.hps_io_hps_io_gpio_inst_LOANIO48 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO48>), //                     .hps_io_gpio_inst_LOANIO48
		.hps_io_hps_io_gpio_inst_LOANIO49 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO49>), //                     .hps_io_gpio_inst_LOANIO49
		.hps_io_hps_io_gpio_inst_LOANIO50 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO50>), //                     .hps_io_gpio_inst_LOANIO50
		.hps_loan_io_in                   (<connected-to-hps_loan_io_in>),                   //          hps_loan_io.in
		.hps_loan_io_out                  (<connected-to-hps_loan_io_out>),                  //                     .out
		.hps_loan_io_oe                   (<connected-to-hps_loan_io_oe>)                    //                     .oe
	);

